# Generated by Django 6.0.5 on 2026-06-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_comment_updated_at_post_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentvote',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commentvote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='postvote',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postvote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
