# Generated by Django 6.0.5 on 2026-06-24 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_comment_is_edited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_edited',
        ),
    ]
