# Generated by Django 6.0.5 on 2026-10-07 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_add_comment_is_edited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentvote',
            name='is_edited',
        ),
        migrations.RemoveField(
            model_name='postvote',
            name='is_edited',
        ),
    ]
