# Generated by Django 6.0.5 on 2026-10-07 10:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_remove_vote_is_edited'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentvote',
            name='value',
            field=models.SmallIntegerField(choices=[(-1, 'Downvote'), (1, 'Upvote')]),
        ),
        migrations.AlterField(
            model_name='postvote',
            name='value',
            field=models.SmallIntegerField(choices=[(-1, 'Downvote'), (1, 'Upvote')]),
        ),
        migrations.AddConstraint(
            model_name='commentvote',
            constraint=models.CheckConstraint(condition=models.Q(('value__in', [-1, 1])), name='commentvote_value_valid'),
        ),
        migrations.AddConstraint(
            model_name='postvote',
            constraint=models.CheckConstraint(condition=models.Q(('value__in', [-1, 1])), name='postvote_value_valid'),
        ),
    ]
