# Generated by Django 6.0.5 on 2026-10-07 11:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_constrain_vote_values'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='commentvote',
            name='commentvote_value_valid',
        ),
        migrations.RemoveConstraint(
            model_name='postvote',
            name='postvote_value_valid',
        ),
        migrations.AddConstraint(
            model_name='commentvote',
            constraint=models.CheckConstraint(condition=models.Q(('value', -1), ('value', 1), _connector='OR'), name='commentvote_value_valid'),
        ),
        migrations.AddConstraint(
            model_name='postvote',
            constraint=models.CheckConstraint(condition=models.Q(('value', -1), ('value', 1), _connector='OR'), name='postvote_value_valid'),
        ),
    ]
