# Generated by Django 6.0.5 on 2026-10-07 11:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_make_vote_checks_sqlite_safe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commentvote',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='postvote',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='commentvote',
            constraint=models.UniqueConstraint(fields=('comment', 'user'), name='unique_comment_vote_per_user'),
        ),
        migrations.AddConstraint(
            model_name='postvote',
            constraint=models.UniqueConstraint(fields=('post', 'user'), name='unique_post_vote_per_user'),
        ),
    ]
