# Generated by Django 6.0.5 on 2026-10-07 11:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_replace_vote_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(validators=[django.core.validators.RegexValidator(message='This field cannot contain only whitespace.', regex='\\S')]),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(validators=[django.core.validators.RegexValidator(message='This field cannot contain only whitespace.', regex='\\S')]),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='This field cannot contain only whitespace.', regex='\\S')]),
        ),
    ]
