# Generated by Django 6.0.5 on 2026-10-07 11:34

import django.core.validators
import pulse.posts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_add_content_validation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), pulse.posts.validators.validate_image_size]),
        ),
    ]
